# Stage 1: Build
FROM node:21-alpine AS build

# Set the working directory
WORKDIR /usr/src/apparel-galaxy-cart-service

# Copy package.json and package-lock.json first for better caching
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY src/ src/
# COPY tests/ tests/
COPY tsconfig.json tsconfig.json

# Build the TypeScript code
RUN npm run build

# Stage 2: Runtime
FROM node:21-alpine AS runtime

# Set the working directory
WORKDIR /usr/src/apparel-galaxy-cart-service

# Copy only the necessary files from the build stage
COPY --from=build /usr/src/apparel-galaxy-cart-service/dist ./dist
COPY package*.json ./

# Install only production dependencies  --only=production
RUN npm install

# Expose the port the app runs on
# EXPOSE 8088

# Command to run the application
# CMD ["node", "dist/src/server.js"]
CMD ["npm", "run", "start"]
