# Use the official Node.js image as a base
FROM node:21-alpine

# Set the working directory
WORKDIR /usr/src/apparel-galaxy-product-service

# Copy package.json and package-lock.json first for better caching
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY src/ src/
COPY tests/ tests/
COPY tsconfig.json tsconfig.json

# Build the TypeScript code
RUN npm run build

# Expose the port the app runs on
#EXPOSE 8080

# Command to run the application
#CMD ["node", "dist/src/server.js"]
CMD ["npm", "run", "start"]
